### ISSUE TITLE
El código es sensible a inyecciones SQL

### ISSUE THREAD

**Issue by agubelu** [AgoraUS-G1-1617/Recuento-y-modificacion#11]
El código que has hecho está bastante desprotegido contra inyecciones SQL:

`"SELECT * from preguntas where id = " + preguntaId;`

La forma correcta sería

`"SELECT * from preguntas where id = ?";`
Y luego ejecutarlo con
`db.run(command, [preguntaId]);`

**Comment by rafgardom** [comment]
Tienes razón, corregido en el último commit
