### ISSUE TITLE
Adición de atributo Código Postal a la votación

### ISSUE THREAD

**Issue by anddonram** [AgoraUS-G1-1617/Recuento-y-modificacion#12]
Buenas tardes,
Me pasaba por aquí y he decidido dejaros un regalito, espíritu navideño.
Tal y como le pedimos a Creación y Admin de votaciones en una issue, que parece un poco no actualizándose, (https://github.com/AgoraUS-G1-1617/Creacion-admin-de-votaciones/issues/6), solicitamos que pudierais añadir el campo código postal a la votación(si es posible, llamadlo cp) para que podamos consumir (provisional o definitivamente) vuestra API. No importa si es texto o un número, lo ideal sería que fuera un entero de cinco dígitos, pero no es imprescindible.
Muchas gracias por su paciencia.

**Comment by agubelu** [comment]
Para mañana lo tenéis
