### ISSUE TITLE
La API de recuento ha petado (es broma) / Añadir encuesta finalizada

### ISSUE THREAD

**Issue by anddonram** [AgoraUS-G1-1617/Recuento-y-modificacion#16]
Saludos en este día de los inocentes! Estaba comprobando método de recuento recién salido del horno y todas las encuestas guardadas en vuestro sistema están abiertas. ¿Podríais poner una cerrada para que podamos acceder al recuento?
Muchas gracias.

**Comment by agubelu** [comment]
Buenas. Añadir una encuesta ya finalizada directamente a nuestra base de datos es algo difícil, ya que el archivo de base de datos está en gitignore y tendríamos que subirlo manualmente al servidor de integración continua. 

Creo que la mejor opción es que vosotros mismos creéis una votación a través de nuestra API y le pongáis una fecha de cierre cercana (el único límite en este sentido es que la fecha de cierre debe estar en el futuro, pero no hay ninguna duración mínima), por ejemplo, que cierre mañana, y creáis algunos votos en ella. Así, mañana mismo tendríais una votación cerrada con algunos votos para que podáis hacer vuestras cosas.

Un saludo.

**Comment by anddonram** [comment]
Muy buena opción, no se me había ocurrido. En seguida me pongo.

Edit: he creado una como has sugerido y, pensado que acabaría pronto, me he dado cuenta de que la fecha de creación que guarda es una hora menos que la actual. ¿Es un bug o el servidor está en Canarias?

**Comment by agubelu** [comment]
Pues tiene pinta de ser un bug, a no ser que @ManuelLR haya puesto el server en Tenerife para que no pase frío. En cualquier caso, lo gestionamos en la issue correspondiente.

**Comment by ManuelLR** [comment]
Chavales, que no cunda el pánico. Debido a las lluvias me tuve que fugar con el servidor a Canarias porque allí no hay huevos de pararlo (además de tener 1 hora más para entregar los trabajos). Fuera de coñas, comenté algo similar en el #17
