### ISSUE TITLE
Desfase horario en la creación de las votaciones

### ISSUE THREAD

**Issue by anddonram** [AgoraUS-G1-1617/Recuento-y-modificacion#17]
Saludos compañeros de recuento,
estuve probando su API para crear una votación, tal como dije en #16 , y cuando vi que llegó la hora de cerrar las urnas, la URL de recuento me seguía diciendo que aún no había cerrado la encuesta.
Haciendo debug en mi navegador, descubrí que el objeto votación recibido tenía como fecha de creación, una hora antes de la hora en la que había creado el objeto.
Esperaba que la fecha de creación se adaptara a la zona horaria de la persona que lo crea.
Por si aporta algo relevante, estoy usando Chrome.

De nuevo, saludos y gracias.

**Comment by agubelu** [comment]
Buenas. Mañana le echo un vistazo al problema, que hoy he tenido el día algo ajetreado con asuntos navideños.

**Comment by ManuelLR** [comment]
Hola, ya me conoceréis, me ahorro presentaciones. 
El servidor tiene la hora mal puesta (concretamente una hora menos). Teniendo todo desplegado no creo que haya ningún tipo de error pero probando en local puede que la cosa cambie. Yo las pruebas las realizo con algo desplegado (creo que es habitual y así puedes hacer pruebas de carga y comportamiento) pero, si realmente necesitais que la hora esté bien, ponedme un issue en el continuous-delivery-integration y lo miro cuando pueda. 
Felices fiestas!

**Comment by agubelu** [comment]
El problema está en que cuando se crea una votación se le asigna una fecha y hora de cierre, y el que la crea interpreta que esta hora está en su horario local. Quizá sea difícil hacerlo para que detecte automáticamente el huso horario del que envía la petición (¿se puede hacer eso con simples peticiones HTTP?) por lo que creo que lo más conveniente es simplemente ajustar la hora del servidor a la española.

**Comment by agubelu** [comment]
Debería estar arreglado en https://github.com/AgoraUS-G1-1617/continuous-integration-agoraus_g1/commit/db429efdac5f3a8226f5f619e616ba2b1fc01108

**Comment by rafgardom** [comment]
Corregido y comprobado

**Comment by ManuelLR** [comment]
Bien hecho chicos !
