### ISSUE TITLE
El parámetro de ID  de votación no es necesario para eliminar o modificar un voto

### ISSUE THREAD

**Issue by agubelu** [AgoraUS-G1-1617/Recuento-y-modificacion#9]
El identificador de la pregunta es único para todas las preguntas almacenadas, por lo que no es necesario indicar la votación.

**Comment by rafgardom** [comment]
Claro que es único, ¿puedes indicarme dónde te chirría el identificador de la votación?

**Comment by agubelu** [comment]
En el módulo de modificación:

https://github.com/AgoraUS-G1-1617/Recuento-y-modificacion/blob/crud_encuestas/modificationModule.js

En los métodos changeVote y deleteVote

**Comment by rafgardom** [comment]
Vale, ya he visto a qué te referías y si, te lo compro. Ya están subidos los cambios.
